# Gitleaks Configuration for MCP Agent Repository
# This configuration scans for secrets and sensitive information

title = "MCP Agent Secrets Detection"
version = "8.18.0"

# Enable verbose output for better debugging
verbose = true

# Scan configuration
[scan]
  # Scan all files in the repository
  path = "."
  
  # Use git history for scanning
  git = true
  
  # Include untracked files
  untracked = true
  
  # Scan depth (0 = unlimited)
  depth = 0
  
  # Include binary files
  binary = false
  
  # Include symlinks
  symlinks = true

# Output configuration
[output]
  # Output format (json, sarif, csv, or noop)
  format = "json"
  
  # Output file path
  path = "gitleaks-report.json"
  
  # Include additional metadata
  verbose = true

# Allowlist configuration - files and patterns to ignore
[allowlist]
description = "Files and directories to ignore"
paths = [
  '''frontend/package-lock.json''', # Ignore package-lock.json due to many false positives
  '''frontend/yarn.lock''', # Ignore yarn.lock due to many false positives
  '''frontend/node_modules/''', # Ignore node_modules
  '''agent_go/logs/''', # Ignore log files
  '''agent_go/cache/''', # Ignore cache files
  '''agent_go/bin/''', # Ignore binaries
  '''agent_go/tool_output_folder/''', # Ignore tool output folder
  '''agent_go/large_tool_output/''', # Ignore large tool output folder
  '''agent_go/go.sum''', # Ignore go.sum due to many false positives from module hashes
  '''planner/go.sum''', # Ignore planner go.sum due to many false positives from module hashes
  '''external_example/agent_modes/go.sum''', # Ignore external example go.sum
  '''external_example/structured_output_test/go.sum''', # Ignore external example go.sum
  '''external_example/agent_with_events/go.sum''', # Ignore external example go.sum
  '''external_example/api/go.sum''', # Ignore external example go.sum
  '''external_example/custom_logging/go.sum''', # Ignore external example go.sum
  '''external_example/langfuse_test/go.sum''', # Ignore external example go.sum
  '''memory/venv/''', # Ignore Python virtual environment (contains cryptographic hashes and certificates)
  '''memory/.venv/''', # Ignore Python virtual environment (contains cryptographic hashes and certificates)
  '''planner-docs/.git/''', # Ignore git index files (contains file hashes)
  '''planner-docs/.git/index''', # Ignore git index files (contains file hashes)
  '''.git/index''', # Ignore git index files (contains file hashes)
  '''logs/''', # Ignore log files (contain secrets but are logs)
  '''planner-docs/Tasks/''', # Ignore planner docs (contain example data)
  '''orchestrator-patterns.md''', # Ignore documentation (contains example data)
  '''agent_go/.env.backup''', # Ignore backup env files (contain real secrets but are backups)
  '''agent_go/pkg/external/ENV_GUIDE.md''', # Ignore ENV guide (contains example secrets)
  '''bugs-tasks-complete-progress/''', # Ignore bug documentation files
  '''bug.md''', # Ignore bug documentation files
  '''configs/mcp_servers_clean.json''', # Example config, no real secrets
  '''configs/mcp_servers_clean_user.json''', # Example config, no real secrets
  '''configs/mcp_servers_clean_user_with_aws.json''', # Example config, no real secrets
  '''configs/mcp_servers.json''', # Example config, no real secrets
  '''configs/mcp_servers_actual.json.example''', # Example config, no real secrets
  '''configs/mcp_servers_actual.json''', # This file should be in .gitignore, but if it's not, ignore it here
  '''env.example''', # Example environment file, no real secrets
  '''agent_go/env.example''', # Example environment file, no real secrets
  '''agent_go/service-account.json''', # Google Cloud service account key (should be in .gitignore)
  '''gitleaks-report.json''', # Ignore gitleaks report itself
  '''gitleaks-current-scan.json''', # Ignore current scan report
  '''gitleaks-test.json''', # Ignore test scan report
  '''gitleaks-final-test.json''' # Ignore final test scan report
]

# Rules configuration
[[rules]]
  id = "aws-access-key"
  description = "AWS Access Key ID"
  regex = '''(AKIA[0-9A-Z]{16})'''
  tags = ["aws", "key", "access-key"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "aws-secret-key"
  description = "AWS Secret Access Key"
  regex = '''([A-Za-z0-9/+=]{40})'''
  tags = ["aws", "secret", "access-key"]
  entropy = 4.0
  secretGroup = 1

[[rules]]
  id = "openai-api-key"
  description = "OpenAI API Key"
  regex = '''(sk-[A-Za-z0-9]{48})'''
  tags = ["openai", "api-key"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "anthropic-api-key"
  description = "Anthropic API Key"
  regex = '''(sk-ant-[A-Za-z0-9]{48})'''
  tags = ["anthropic", "api-key"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "github-pat"
  description = "GitHub Personal Access Token"
  regex = '''(ghp_[A-Za-z0-9]{36})'''
  tags = ["github", "token"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "github-app-token"
  description = "GitHub App Token"
  regex = '''(gho_[A-Za-z0-9]{36})'''
  tags = ["github", "token", "app"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "langfuse-public-key"
  description = "Langfuse Public Key"
  regex = '''(pk_[A-Za-z0-9]{32})'''
  tags = ["langfuse", "public-key"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "langfuse-secret-key"
  description = "Langfuse Secret Key"
  regex = '''(sk_[A-Za-z0-9]{32})'''
  tags = ["langfuse", "secret-key"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "generic-api-key"
  description = "Generic API Key"
  regex = '''[Aa][Pp][Ii][_-]?[Kk][Ee][Yy][_-]?[=:]\s*['"]?([A-Za-z0-9]{20,})['"]?'''
  tags = ["api-key", "generic"]
  entropy = 3.0
  secretGroup = 1

[[rules]]
  id = "database-connection"
  description = "Database Connection String"
  regex = '''(?:mysql|postgresql|mongodb|redis)://[^:\s]+:([^@\s]+)@[^/\s]+'''
  tags = ["database", "connection"]
  entropy = 2.5
  secretGroup = 1

[[rules]]
  id = "slack-bot-token"
  description = "Slack Bot Token"
  regex = '''(xoxb-[0-9]{11}-[0-9]{11}-[A-Za-z0-9]{24})'''
  tags = ["slack", "bot", "token"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "slack-app-token"
  description = "Slack App Token"
  regex = '''(xapp-[0-9]{11}-[0-9]{11}-[A-Za-z0-9]{24})'''
  tags = ["slack", "app", "token"]
  entropy = 3.5
  secretGroup = 1

[[rules]]
  id = "sentry-dsn"
  description = "Sentry DSN"
  regex = '''https://([a-f0-9]{32})@[a-z0-9.-]+\.sentry\.io/[0-9]+'''
  tags = ["sentry", "dsn"]
  entropy = 3.0
  secretGroup = 1

[[rules]]
  id = "grafana-api-key"
  description = "Grafana API Key"
  regex = '''eyJrIjoi([A-Za-z0-9]{20,})'''
  tags = ["grafana", "api-key"]
  entropy = 3.5
  secretGroup = 1

# Exclude patterns (files/directories to ignore)
[[rules.exclude]]
  # Exclude example files
  path = '''.*\.example'''
  
[[rules.exclude]]
  # Exclude test files
  path = '''.*test.*'''
  
[[rules.exclude]]
  # Exclude documentation
  path = '''.*\.md$'''
  
[[rules.exclude]]
  # Exclude node_modules
  path = '''node_modules/'''
  
[[rules.exclude]]
  # Exclude vendor directories
  path = '''vendor/'''
  
[[rules.exclude]]
  # Exclude build artifacts
  path = '''dist/'''
  
[[rules.exclude]]
  # Exclude cache directories
  path = '''cache/'''
  
[[rules.exclude]]
  # Exclude log files
  path = '''.*\.log$'''
  
[[rules.exclude]]
  # Exclude gitleaks reports
  path = '''gitleaks-report\.json'''
