#!/bin/bash
echo "=== Debugging Preset Tool Selection ==="
echo ""
echo "Run these commands in your browser console (F12):"
echo ""
echo "1. Check if presets have '*' markers:"
echo "   const state = JSON.parse(localStorage.getItem('global-preset-storage'));"
echo "   console.log('Presets:', state.customPresets.map(p => ({label: p.label, tools: p.selectedTools})));"
echo ""
echo "2. Check current preset state:"
echo "   console.log('Current tools:', state.currentPresetTools);"
echo ""
echo "3. Check if any preset has '*' markers:"
echo "   state.customPresets.forEach(p => {"
echo "     if (p.selectedTools?.some(t => t.endsWith(':*'))) {"
echo "       console.log('Found all-tools marker:', p.label, p.selectedTools);"
echo "     }"
echo "   });"
