services:
  # Ollama service for embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: graphiti-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Graphiti Knowledge Graph API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_BGE_RERANKER=false
    container_name: graphiti-api
    ports:
      - "8055:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./models:/app/models
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=false
      - OLLAMA_BASE_URL=http://ollama:11434/v1
      - KUZU_DB=/app/data/graphiti.kuzu
      - USE_BGE_RERANKER=false
      - BGE_MODEL_NAME=BAAI/bge-reranker-v2-m3
      - BGE_MODEL_CACHE_DIR=/app/models/bge-reranker
    depends_on:
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Kuzu Explorer for visual graph exploration (read-only)
  # Note: Disabled by default due to Kuzu DB locking limitations
  # Even READ_ONLY mode cannot run concurrently with READ_WRITE API
  # Uncomment the lines below to enable (requires stopping API first)
  # explorer:
  #   image: kuzudb/explorer:latest
  #   container_name: graphiti-explorer
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./data:/database
  #   environment:
  #     - KUZU_FILE=graphiti.kuzu
  #     - MODE=READ_ONLY
  #   restart: unless-stopped

volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: graphiti-network
