FROM neo4j:5.15-community

# Switch to root to install packages
USER root

# Install APOC plugin
RUN wget -O /var/lib/neo4j/plugins/apoc.jar https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/5.15.0/apoc-5.15.0-core.jar

# Create vector similarity functions as a custom procedure
RUN echo 'package vector.similarity;' > /tmp/VectorSimilarity.java && \
    echo '' >> /tmp/VectorSimilarity.java && \
    echo 'import org.neo4j.procedure.Description;' >> /tmp/VectorSimilarity.java && \
    echo 'import org.neo4j.procedure.Name;' >> /tmp/VectorSimilarity.java && \
    echo 'import org.neo4j.procedure.UserFunction;' >> /tmp/VectorSimilarity.java && \
    echo '' >> /tmp/VectorSimilarity.java && \
    echo 'import java.util.List;' >> /tmp/VectorSimilarity.java && \
    echo '' >> /tmp/VectorSimilarity.java && \
    echo 'public class VectorSimilarity {' >> /tmp/VectorSimilarity.java && \
    echo '    ' >> /tmp/VectorSimilarity.java && \
    echo '    @UserFunction("vector.similarity.cosine")' >> /tmp/VectorSimilarity.java && \
    echo '    @Description("Calculate cosine similarity between two vectors")' >> /tmp/VectorSimilarity.java && \
    echo '    public Double cosineSimilarity(@Name("vector1") List<Double> vector1, @Name("vector2") List<Double> vector2) {' >> /tmp/VectorSimilarity.java && \
    echo '        if (vector1 == null || vector2 == null || vector1.size() != vector2.size()) {' >> /tmp/VectorSimilarity.java && \
    echo '            return 0.0;' >> /tmp/VectorSimilarity.java && \
    echo '        }' >> /tmp/VectorSimilarity.java && \
    echo '        ' >> /tmp/VectorSimilarity.java && \
    echo '        double dotProduct = 0.0;' >> /tmp/VectorSimilarity.java && \
    echo '        double norm1 = 0.0;' >> /tmp/VectorSimilarity.java && \
    echo '        double norm2 = 0.0;' >> /tmp/VectorSimilarity.java && \
    echo '        ' >> /tmp/VectorSimilarity.java && \
    echo '        for (int i = 0; i < vector1.size(); i++) {' >> /tmp/VectorSimilarity.java && \
    echo '            double v1 = vector1.get(i);' >> /tmp/VectorSimilarity.java && \
    echo '            double v2 = vector2.get(i);' >> /tmp/VectorSimilarity.java && \
    echo '            dotProduct += v1 * v2;' >> /tmp/VectorSimilarity.java && \
    echo '            norm1 += v1 * v1;' >> /tmp/VectorSimilarity.java && \
    echo '            norm2 += v2 * v2;' >> /tmp/VectorSimilarity.java && \
    echo '        }' >> /tmp/VectorSimilarity.java && \
    echo '        ' >> /tmp/VectorSimilarity.java && \
    echo '        if (norm1 == 0.0 || norm2 == 0.0) {' >> /tmp/VectorSimilarity.java && \
    echo '            return 0.0;' >> /tmp/VectorSimilarity.java && \
    echo '        }' >> /tmp/VectorSimilarity.java && \
    echo '        ' >> /tmp/VectorSimilarity.java && \
    echo '        return dotProduct / (Math.sqrt(norm1) * Math.sqrt(norm2));' >> /tmp/VectorSimilarity.java && \
    echo '    }' >> /tmp/VectorSimilarity.java && \
    echo '}' >> /tmp/VectorSimilarity.java

# Compile and install the custom function
RUN cd /tmp && \
    javac -cp "/var/lib/neo4j/lib/*" VectorSimilarity.java && \
    jar cf vector-similarity.jar VectorSimilarity.class && \
    mv vector-similarity.jar /var/lib/neo4j/plugins/ && \
    rm VectorSimilarity.java VectorSimilarity.class

# Set permissions
RUN chown -R neo4j:neo4j /var/lib/neo4j/plugins

# Switch back to neo4j user
USER neo4j

# Expose ports
EXPOSE 7474 7687

# Start Neo4j
CMD ["neo4j"]
