package server

const upgradeRouteSummaries = `WORKFLOW CONTRACT UPGRADE: ROUTE-SPECIFIC DAILY ACTIONS AND PULSE SUMMARIES.

Routes (planning steps of type routing) represent major sub-workflows; branch steps represent small decisions inside them. Do only this reporting migration. Read reporting-policy and design-reporting-ui, then inspect the real routing steps, existing notification-producing descriptions, and db/reports/index.html if present.

The existing notify_user tool accepts summary_routes: one array entry per route represented by the actual evidence, with routing_step_id, route_id, readable label, title, status, message and optional fields/sections. Prefer this to the legacy summary_route string. One call still sends one digest through existing configured channels; shared work stays in top-level message/sections. The backend renders route entries for external delivery; do not author a duplicate per-channel copy. Run summaries use actual execution receipts; Pulse summaries use actual review scope. Never infer review coverage from a scheduled route, mark an unreviewed route clean, or copy workflow-wide costs into each route.

If this workflow has major routes, update existing notification-producing instructions through normal typed plan tools where needed; do not add steps, new notification calls, schedules, recipients, or channels. Make the existing Daily Action / Recent Activity report group or filter the existing org_dashboard_notifications rows by the routing_step_id/route_id pairs inside route_summaries_json, showing each route's actions and status. Use summary_text for the shared lead plus typed route entries; message remains the full rendered digest for backward-compatible fallback, so do not display it again beside the same route bodies. Preserve shared work, actual timestamps, explicit legacy Route labels and unknown historical scope. Inspect the real schema first; an absent notification table or route_summaries_json column must render an honest fallback to original message/fields, never fail the page. Do not backfill historical route identities. Preserve an explicitly requested custom activity source and add grouping only when its existing evidence supports it. If there are no major routes, leave the workflow unchanged.

Do not delete steps/tables or change the workflow's business behavior. Do not execute the workflow or send a notification during this migration. Validate changed plan artifacts with validate_plan_change and changed HTML with validate_report_html, and re-read changes before stamping. After successful validation, or a verified no-op, call set_workflow_contract_version(version="1.0.40") and stop. Do not stamp on a failed validation or invent route attribution to finish the upgrade.`
