package server

const upgradeExplicitSchedulePulse = `WORKFLOW CONTRACT UPGRADE: EXPLICIT PULSE POLICY FOR EVERY SCHEDULE.

Do only this migration. Load read_skill(skills=[{"name":"builder-reference","path":"references/schedules.md"}]). Read workflow.json and list_schedules, the plan's route definitions, each schedule's route_selections or messages, frequency, and relevant retained run/review evidence. Decide across the workflow's complete schedule set, including disabled schedules and calendar schedules. Account for token cost and whether reviewing multiple runs together yields stronger evidence than reviewing each run separately. Choose a review cadence supported by the existing schedule timings, evidence maturity and run retention; record that cadence and the retained evidence window in pulse_mode_reason.

Persist pulse_mode (off, basic, or full) AND a non-empty pulse_mode_reason on EVERY schedule using update_schedule. Decide deliberately; do not mechanically copy pulse.enabled or assign full to every route. Preserve an existing explicit mode unless the evidence justifies a change; add its missing reason. The reason must describe this schedule's actual purpose/frequency, why review is or is not needed after each occurrence, and any review-coverage dependency by schedule ID or route. Merely repeating the chosen mode is not a useful reason.

Prefer basic for frequent routine operations: it retains backup, report publication and run-summary notification while skipping Gate/review/repair. Choose full where evidence, risk and cadence justify the review cost. External actions or durable writes alone do not require full after every occurrence. If basic relies on another schedule's full review, verify that review can actually inspect this route's retained evidence; do not assume a full run on route A automatically covers route B. If coverage is uncertain, retain full for the affected schedule with a concrete reason rather than inventing coverage or changing review behavior in this migration. Use off only when no post-run backup/publication/notification is intentionally needed, including preserving an existing disabled workflow Pulse policy; explain that consequence. Do not invent owner approval to turn off stewardship.

Do not change cron expressions, timezones, route selections, schedule IDs, enabled states, messages, plan steps, backup destinations, or workflow Pulse defaults. Do not create or delete schedules, including a legacy pulse_review_only schedule. Do not execute the workflow, run Pulse, publish, send notifications, or perform public actions. Updating the existing schedules' Pulse policy fields is the entire scope.

Re-read workflow.json and list_schedules. Confirm every schedule, including disabled/calendar entries, has an allowed explicit mode and a meaningful reason, and all unrelated fields are preserved. A workflow with no schedules needs no invented schedule and can pass. Record a compact schedule/mode/reason summary. If any schedule is incomplete or a save fails, report the exact blocker and do not stamp. Only then call set_workflow_contract_version(version="1.0.41") and stop. The stamp validates all persisted schedule policy fields; an incomplete migration cannot be acknowledged.`
