package videoproduct

// The two cinematic pipelines are separate because a 12-minute narrated piece
// and a 30-second
// social cut are different productions, not one production at two lengths:
// long-form needs chapters, retention management, character continuity across
// dozens of clips, and narration that the visuals are cut to. Short-form needs
// one arc landed in the first seconds and nothing else.
//
// Both can spend real money per generation call. That is why every stage
// here that can spend is gated on explicit authorization in its own human
// input, using the same rule the assets stage established.

// generationSpendGate is the authorization paragraph every paid stage carries.
// Kept in one place so the stages that spend cannot drift apart on what counts
// as approval; a test pins exactly which stages carry it.
//
// The rule is deliberately strict about WHERE approval comes from: this
// product bills the user per generation call, and an agent that reads
// enthusiasm about a storyboard as permission to spend is the failure mode
// worth designing against.
func generationSpendGate(what string) string {
	return "This stage can spend the user's money, so it has exactly two modes and you choose between them ONLY from the human input for THIS stage. " +
		"Treat generation as authorised solely when that input explicitly approves generating " + what + " or spending on it. " +
		"Approval of an earlier stage, enthusiasm about the plan, or silence is NOT authorisation.\n" +
		"MODE A — not explicitly authorised (the default): plan the work completely and produce nothing. Write the artifact this stage owes, with every intended call fully specified — resolved model id, provider, exact input, and the estimated number of paid calls — so the user can approve a concrete, costed plan rather than an idea. Finish by stating plainly what it will cost and what still needs approval.\n" +
		"MODE B — explicitly authorised: do the same planning, then actually make the calls, staying within any cost ceiling or call count this pipeline's brief recorded. Never record an asset as produced unless you created the file and confirmed it exists on disk and is non-empty; a call that fails is recorded as `failed` with its error, never described as if it succeeded. If you reach the approved ceiling before finishing, stop and report what remains rather than continuing to spend."
}

// A spending approval alone must not silently lock a recurring subject to an
// agent-selected model: that choice governs every later appearance.
func characterModelChoiceGate() string {
	return "Before creating any reference image, present at most three live-verified viable character-model choices. For each state the exact provider and model id, why its reference-image conditioning fits this subject, relevant output/control limits, and current billing evidence; recommend one, but NEVER silently select it. Ask the user to choose a named option (or name another model) in this stage's human input. A generic approval to make characters, an earlier provider preference, or a budget approval without a model choice is NOT a character-model selection. Do not make any paid character-reference call until that input contains both the selected provider/model and explicit approval to spend on the stated reference pack. Record the user's selected provider/model, pack, retry allowance, and cost evidence in the character artifact. "
}

var longformStageDescriptions = map[string]string{
	"longform-brief": "Own the brief before any production work. Read the request, the recent conversation, and every relevant file in uploads/. " +
		"This pipeline is for genuinely long-form video — roughly 8 minutes or more — so confirm the target duration explicitly rather than assuming; if the user actually wants something short, say so and stop rather than running a long-form production on a short brief. " +
		"Follow video-creation's request-understanding rules, and resolve the production-level unknowns video-model-selection lists before the first paid call, because every one of them is expensive to unwind later: provider or model preference, whether any character/presenter/product must recognisably recur across shots, the cost ceiling or maximum number of paid generation calls, and how many re-prompts a disappointing shot gets before you stop and ask. " +
		"Use longform-cinematic-video and video-storytelling to decide the narrative and cinematic contract at this length — which arc, which hook type, roughly how many chapters, visual language, camera grammar, color journey, sound world, and continuity priorities. " +
		"Write longform-brief.md with the message, audience, destination, target duration, aspect ratio, tone, narrative shape, cinematic contract, every resolved production decision above, the exact claims and their sources, assumptions, and blockers. Do not generate media and do not write the script yet.",

	"longform-script": "Turn longform-brief.md into longform-script.md, the piece's narrative spine. Follow video-storytelling: one arc across the whole piece, chapters of roughly 2-4 minutes each carrying their own smaller arc, beats connected with `but`/`therefore` rather than `and then`, and the hook and stakes fully landed inside the first 30 seconds. " +
		"Place the retention work deliberately: the first major payoff before 2:00, a re-hook every 3-4 minutes after the two-minute mark, an open loop planted early and paid off late, and pattern interrupts at the cadence the skill gives. Reserve the last ~20 seconds for the close and put no essential content there. " +
		"Write the narration verbatim — this exact text becomes the voiceover and drives every downstream duration, so it must be the words to be spoken, not a summary of them. Mark chapter and sequence boundaries, and for each beat state what the viewer should see, what is said, the dramatic turn it serves, and which claim or source it rests on. " +
		"Name every character, presenter, or product that recurs across more than one beat; the next stage defines them. Do not generate media.",

	"longform-characters": "Define every recurring character, presenter, or product BEFORE any shot of it exists. This is the first paid-media decision in a cinematic production: the brief and script establish what the subject must do, then its reference must be approved before footage can be planned or made. This stage prevents the most common viewer-visible defect in AI-generated video — a face, outfit, or product appearance drifting between shots — and it cannot be done retroactively. " +
		"Read longform-brief.md and longform-script.md and follow video-cinematography's character rules. For each recurring subject produce both deliverables: a written spec at characters/<name>.md carrying 3-6 specific disambiguating visual attributes as one exact phrase to be reused verbatim in every later prompt, and a generated reference image at characters/<name>.png. Keep both inside this step's own folder. " +
		"After the user chooses, commit one model and one provider per character's whole arc — record that choice, because later stages are bound by it and a mid-arc switch needs the user's explicit sign-off. Use video-model-selection to prepare the choices, and fal-ai or google-ai to generate; both skills show how to send and reuse a local reference image. " +
		"Write longform-characters.md listing every subject, its spec path, its reference image path, its user-selected committed model and provider, and any subject the brief mentions that deliberately does NOT recur. After generating a reference, call show_character for each one and wait for explicit approval. The shot list must not plan a recurring subject until its displayed reference is approved. If the brief needs no recurring subject, say so explicitly in longform-characters.md and generate nothing. " +
		characterModelChoiceGate() +
		generationSpendGate("character reference images"),

	"longform-narration": "Generate the narration, because at this length the voiceover is the spine the visuals are cut to — deriving shot durations from an estimate instead of from measured audio is the most expensive mistake in this pipeline, forcing either regenerated clips or a rewritten script. " +
		"Read longform-script.md and follow video-editing's narration guidance. Generate the voiceover in per-beat or per-chapter segments, never as one long pass, so a single bad beat can be regenerated later without re-timing everything after it -- both providers' own guidance independently recommends chunking for the same reason. " +
		"Use whichever provider longform-brief.md committed to: `fal-ai` and `google-ai` both generate speech, so a production with only one provider's key configured is not blocked here. If the brief settled on a provider whose credential is missing, say so and stop rather than silently switching providers mid-production. " +
		"Then MEASURE what you actually got: run ffprobe on every segment and record its real duration. Do not record an estimate from the word count. " +
		"Write longform-narration.md listing each segment's beat id, chapter, script text, file path, and measured duration in seconds, plus the measured total. The next stage derives the entire shot plan from these numbers, so an unmeasured or missing segment is a blocker, not a rounding detail. " +
		generationSpendGate("narration or voiceover audio"),

	"longform-shotlist": "Turn the measured narration into the shot plan. Read longform-brief.md, longform-script.md, longform-characters.md, and longform-narration.md. If a recurring subject exists, proceed only when this step's human input explicitly approves its displayed reference; otherwise write a blocked shot list naming the approval still needed and do not prepare paid calls. " +
		"Derive every duration from longform-narration.md's MEASURED numbers — a chapter whose narration measures 94 seconds needs 94 seconds of visuals, and how many clips that is falls out of the chosen model's per-call duration, not the other way round. Do the arithmetic explicitly and show it. Plan chapters, sequences, and scenes before individual shots, and minimize independent calls and stitch points using the topology rules in longform-cinematic-video and video-provider-capabilities. " +
		"For each shot record: its beat and chapter, its duration, what the shot must prove, the resolved model id and provider, and the full generation prompt built with video-cinematography's five-aspect formula — subject, subject motion, scene, spatial framing, camera — using precise camera vocabulary rather than mood adjectives. Any shot containing a recurring subject MUST use that subject's committed model and provider from longform-characters.md and repeat its spec phrase verbatim; where that model's audio support is wrong for the shot, plan it silent and add audio at assembly rather than switching models. " +
		"Classify every visual as generated cinematic footage, supplied media, or a HyperFrames insert. Use a HyperFrames insert only for exact UI/screens, titles, typography, diagrams, overlays, transitions, camera moves over supplied assets, or compositing that the user wants; never use it to fabricate a photoreal subject, performance, location, or continuity-critical shot. Where consecutive clips must flow together, overlap their prompts at the seam so clip N's last described moment matches clip N+1's first. Choose each generated shot's model with video-model-selection and confirm the model id against the provider's own live reference — never invent one. " +
		"Write longform-sequence-plan.json with every sequence's incoming and outgoing state, references, generation topology, boundary plan, transition grammar, seam risk, and the reason each independent generation is unavoidable. Write longform-shotlist.md with the total paid call count and estimated cost stated up front, since the next stage asks the user to approve exactly that. Generate nothing in this stage.",

	"longform-generate": "Produce the shots. Read longform-shotlist.md, longform-sequence-plan.json, longform-characters.md, and longform-narration.md, and create strictly what longform-shotlist.md specifies — this stage executes a plan the user approved, it does not re-plan. Generate sequence by sequence and use fal-ai, google-ai, or seeddance-api per the provider and model recorded for each generated shot. For an entry explicitly classified as a HyperFrames insert, build and render only that insert with the managed HyperFrames tooling, preserve the cinematic design contract, and show its MP4 for review; do not introduce unplanned HyperFrames scenes. " +
		"Condition every shot containing a recurring subject on that subject's reference image from longform-characters.md, using the committed model and provider and the exact spec phrase; upload each reference once and reuse the returned handle across shots rather than re-uploading per call. " +
		"Respect the re-prompt budget recorded in longform-brief.md: when a shot misses, re-prompt with more specific technical direction rather than a stronger adjective, and stop at the budget to ask rather than spending indefinitely on one stubborn shot. " +
		"Preserve the sequence plan's reference order and incoming/outgoing state, show each generated clip individually, and reject continuity contradictions before assembly. Write longform-continuity-ledger.json with accepted and rejected versions, request lineage, usable trim range, boundary frames, actual incoming/outgoing state, audio state, and legal successor for every clip. " +
		"Write longform-generation.md recording, per shot: status (`generated`, `failed`, or `skipped`), the exact local file path when one exists, the resolved model id and provider, the prompt actually sent, the seed if any, and the measured duration of what came back. A shot recorded as generated without a file on disk is a failure, not a bookkeeping detail. " +
		generationSpendGate("video, image, or audio clips"),

	"longform-assemble": "Assemble the finished video from media that already exists. Read longform-shotlist.md, longform-sequence-plan.json, longform-continuity-ledger.json, longform-narration.md, and longform-generation.md, and resolve every input from the exact paths recorded there — do not write generation prompts, do not call any generation provider, and do not look for files elsewhere. If a required shot is `failed` or missing, stop and write longform-render.md naming what is missing; never substitute an unrelated clip. HyperFrames may supply exact overlays, titles, transitions, or approved inserts, but must remain inside the same cinematic edit and sound world. " +
		"Follow video-editing throughout. Cut the visuals to the measured narration rather than the reverse. Verify every clip's specs with ffprobe before concatenating and normalise the minority that does not match, since one differently-specced clip breaks a stream-copy concat for the whole batch. Force constant frame rate where a source is variable, or audio drift accumulates audibly across a piece this long. " +
		"Follow longform-cinematic-video's cut grammar. Build and inspect one representative assembled sequence before committing to the full film. Use cuts on action, match cuts, and J/L audio bridges where motivated; never use a dissolve to hide incompatible identity or geography. Keep one continuous music and ambience world across the whole runtime rather than restarting a cue per chapter, hit the stated per-stem levels and the -14 LUFS / -1 dBTP delivery target, and keep per-chapter loudness within about 2 LUFS so no chapter reads louder than its neighbours. Put exact text, titles, and captions in a deterministic overlay layer, never baked into generated footage. " +
		"Write longform-edit-decision-list.json with every source version, in/out point, timeline time, cut type, audio lead/trail, transition, grade, speed change, and linked narration beat. Render longform-final.mp4 in this step folder, verify it by full decode with ffprobe, and write longform-render.md with every input path, the commands used, and the measured duration, dimensions, frame rate, codecs, and loudness of the result.",

	"longform-check": qualityReviewDescription("longform-final.mp4 as named by longform-render.md", "longform-delivery.md") +
		" This is a long-form piece assembled from many independently-generated clips, so weight the review accordingly: produce one contact sheet per chapter rather than one unreadable sheet for the whole runtime, and cover every edit boundary across the set rather than sampling a few. " +
		"After video-quality's checks pass, run generated-video-quality's checks against the same candidate and add their results to the same quality-report.json: character_consistency (against every reference image in longform-characters.md, not from memory — drifting identity is this pipeline's characteristic defect and it is invisible unless compared directly), generation_artifacts, temporal_coherence at every stitch point, motion_plausibility, lip_sync where dialogue exists, clip_color_consistency, prompt_adherence against longform-shotlist.md, and narration_alignment against longform-narration.md's measured durations. Write longform-seam-report.json covering EVERY edit boundary with preceding/following source versions, boundary-frame evidence, cut type, visual/action/screen-direction/identity/lighting/audio checks, and verdict. A candidate that passes technical QA but fails any seam is not ready to present. " +
		"Also verify the narrative promises longform-script.md made: the hook lands inside the first 30 seconds, each chapter pays off, the open loop planted early is actually resolved, and the ending delivers the message the brief asked for.",
}

var longformPipeline = &Pipeline{
	ID:          "longform",
	Name:        "Long-form cinematic video",
	Description: "A genuinely long-form (8+ minute) cinematic film built as continuity-controlled sequences, then stitched with narration-driven timing, deliberate picture grammar, and continuous sound.",
	WhenToUse:   "Long-form narrative or explainer video — roughly 8 minutes or more — where the footage must be generated rather than composed from uploads, especially anything with a recurring character, presenter, or product.",
	Stages: []PipelineStage{
		{ID: "longform-brief", Title: "Brief and cinematic direction", Summary: "Lock the story, duration, cost ceiling, visual language, sound world, and continuity priorities.", Output: "longform-brief.md", Skills: []string{"video-creation", "longform-cinematic-video", "video-storytelling", "video-provider-capabilities", "kling-video", "seedance-video", "seeddance-api", "veo-video", "minimax-h3-video", "gemini-omni-video", "video-model-selection"}},
		{ID: "longform-script", Title: "Script and sequences", Summary: "Write the narration, chapter and sequence structure, dramatic turns, and retention beats.", Output: "longform-script.md", Skills: []string{"longform-cinematic-video", "video-storytelling", "video-creation"}},
		{ID: "longform-characters", Title: "Choose and define characters", Summary: "Let the user choose each recurring subject's model, then lock its spec and approved reference before any shot exists.", Output: "longform-characters.md", Skills: []string{"video-cinematography", "video-model-selection", "fal-ai", "google-ai"}},
		{ID: "longform-narration", Title: "Generate narration", Summary: "Produce the voiceover in segments and measure its real duration.", Output: "longform-narration.md", Skills: []string{"video-editing", "fal-ai", "google-ai", "video-storytelling"}},
		{ID: "longform-shotlist", Title: "Sequence and shot plan", Summary: "Design the fewest continuity-controlled sequences, classify generated footage, supplied media, and HyperFrames inserts, then cost the run.", Output: "longform-shotlist.md", Artifacts: []string{"longform-sequence-plan.json"}, Skills: []string{"longform-cinematic-video", "video-cinematography", "video-provider-capabilities", "kling-video", "seedance-video", "seeddance-api", "veo-video", "minimax-h3-video", "gemini-omni-video", "video-model-selection", "video-editing", "hyperframes"}},
		{ID: "longform-generate", Title: "Create sequences", Summary: "Produce and review continuity-controlled footage and any explicitly planned HyperFrames inserts.", Output: "longform-generation.md", Artifacts: []string{"longform-continuity-ledger.json"}, Skills: []string{"longform-cinematic-video", "fal-ai", "google-ai", "seeddance-api", "video-cinematography", "video-provider-capabilities", "kling-video", "seedance-video", "veo-video", "minimax-h3-video", "gemini-omni-video", "video-model-selection", "hyperframes", "hyperframes-cli"}},
		{ID: "longform-assemble", Title: "Cinematic edit and mix", Summary: "Cut on action and meaning, bridge picture and sound, integrate approved HyperFrames layers, and render one coherent film.", Output: "longform-render.md", Artifacts: []string{"longform-final.mp4", "longform-edit-decision-list.json"}, Skills: []string{"longform-cinematic-video", "video-editing", "hyperframes", "hyperframes-cli"}},
		{ID: "longform-check", Title: "Film and seam review", Summary: "Verify the film, every edit boundary, character continuity, sound continuity, HyperFrames inserts, and narrative promises.", Output: "longform-delivery.md", Artifacts: []string{"quality-report.json", "qa-contact-sheet.jpg", "longform-seam-report.json"}, Skills: []string{"longform-cinematic-video", "video-quality", "generated-video-quality", "video-cinematography", "hyperframes-quality"}},
	},
}

var shortformStageDescriptions = map[string]string{
	"shortform-brief": "Own the brief for a short social cut. Read the request, the recent conversation, and every relevant file in uploads/. " +
		"This pipeline is for short-form video — seconds to a couple of minutes. If the brief actually calls for something genuinely long-form, say so and stop rather than compressing a long-form idea into a shape that cannot hold it. " +
		"Follow video-creation's request-understanding rules and resolve the same pre-generation unknowns video-model-selection lists — provider or model preference, whether any subject must recur across shots, the cost ceiling, and the re-prompt budget — because they are just as expensive to unwind here, only faster. " +
		"Confirm the destination platform and aspect ratio explicitly: a vertical cut and a landscape cut are different productions, and safe areas differ per platform. " +
		"Write shortform-brief.md with the message, audience, platform, duration, aspect ratio, tone, the resolved production decisions, exact claims and sources, assumptions, and blockers. Do not generate media.",

	"shortform-script": "Turn shortform-brief.md into shortform-script.md. At this length there is one arc and no chapters: follow video-storytelling's short shape — hook, then value or proof, then the action — and land the hook in the opening seconds, not after a build. Every second must earn the next one. " +
		"Write the narration or on-screen copy verbatim, since it drives the timing of everything downstream, and mark for each beat what the viewer sees and what is said. Keep the piece to the brief's duration; if the idea does not fit, cut the idea rather than rushing the delivery. " +
		"Name any subject that recurs across more than one shot. Do not generate media.",

	"shortform-characters": "Define every recurring character, presenter, or product BEFORE any video shot exists. This is the first paid-media decision: establish the story first, then let the user choose how its recurring subject will be created before any reference-image spend. Read shortform-brief.md and shortform-script.md. If nothing recurs, write shortform-characters.md saying character references are not applicable and generate nothing. " +
		"For each recurring subject, follow video-cinematography and write a stable identity spec with 3-6 distinguishing attributes, then plan a reference pack appropriate to the subject: photoreal people prioritize facial identity, natural skin and coherent anatomy; illustrated characters prioritize silhouette and style; products prioritize exact geometry, colors, logos and markings. Never use HyperFrames or infographic composition to fabricate a supposedly real person. " +
		"Offer three bounded reference-pack choices in shortform-characters.md before spending: budget (one master reference plus one correction), recommended (front, three-quarter, profile and full-body identity views), and premium (the recommended pack plus approved wardrobe, expressions and scene-specific start frames). Give character-image cost and retry allowance separately from video-per-second cost. Present model choices before these pack choices, so the user knows which provider/model will make the pack. " +
		"When generation is explicitly authorised in this step's human input after the user has selected both model and pack, create the selected written specs and reference images under characters/, inspect every image for realism and identity consistency, and record exact paths, provider, model, prompt, cost evidence and status. Call show_character for every generated reference and wait for approval. Write shortform-characters.md last. The next step must not plan shots for a recurring subject until the user has seen and explicitly approved its reference. " +
		characterModelChoiceGate() +
		generationSpendGate("character reference images"),

	"shortform-look-sound": "Lock the production's look and sound before generating narration or footage. Read shortform-brief.md, shortform-script.md, and shortform-characters.md, then follow video-look-sound. Write shortform-look-sound.md as the single durable direction document for every later stage. " +
		"Use visible sections in the document for: `Locations and backgrounds`, `Wardrobe, props, and continuity`, `Lighting and visual palette`, `Camera grammar`, `Speech and voices`, `Music`, `Ambience and sound effects`, and `Captions`. For every spoken beat, classify the speech as off-camera voiceover or visible on-camera dialogue. Record the provider/model or recorded source, voice ID where applicable, language, accent, warmth, pacing, and pronunciation notes. " +
		"When the piece contains people or characters and spoken content, present three speech-design routes BEFORE committing the video model: (1) visible lip-synced dialogue generated natively with the video, (2) one consistent off-camera TTS voiceover over non-speaking performances, and (3) a hybrid with native dialogue for key moments and voiceover for B-roll. Explain the performance/lip-sync result, voice continuity, viable model family, cost, and edit-complexity tradeoff for each; recommend one and require the user's explicit choice. Do not infer voiceover merely because a cheaper or already-considered endpoint lacks audio, and never let an audio-incapable model silently decide the creative format. " +
		"For visible on-camera speech, prefer a video endpoint that generates synchronized native audio and dialogue in the same call; this avoids manufacturing lip sync after the fact. Separate TTS is for off-camera voiceover, not a substitute for a visibly speaking character. Native ambience or Foley may also be preserved when appropriate. For an instructional, tutorial, or explainer brief containing off-camera spoken guidance, require separate TTS voiceover unless the user explicitly approves another audible format. Never silently turn any spoken brief into a silent video. Do not generate media or spend money in this stage.",

	"shortform-narration": "Create the timing spine before any visual clip is planned. Read shortform-brief.md, shortform-script.md, and shortform-look-sound.md. Follow video-look-sound and video-editing. If the direction requires spoken narration, generate the exact approved script in independently replaceable beat-level segments using the selected provider and voice; never make one monolithic pass. " +
		"Run ffprobe on every produced segment and record the REAL measured duration rather than a word-count estimate. Write shortform-narration.md listing each beat id, exact script text, audio path, provider/model/voice, and measured duration in seconds, plus the measured total and any pronunciation or performance issue. Missing, unreadable, silent, or unmeasured required narration is a blocker. " +
		"Only when shortform-look-sound.md classifies every spoken beat as visible native dialogue, or records the user's explicit choice of no spoken track, may separate narration be marked not applicable; record the approved alternate timing source and audio plan so the shot list still has a concrete clock. Off-camera instructional voiceover is not optional merely because a video endpoint can return silent footage. " +
		generationSpendGate("narration or voiceover audio"),

	"shortform-shotlist": "Turn shortform-script.md, shortform-characters.md, shortform-look-sound.md, and shortform-narration.md into shortform-shotlist.md. If a recurring subject exists, proceed only when this step's human input explicitly approves its displayed reference; otherwise write a blocked shot list naming the approval still needed and do not prepare paid calls. Derive every beat and shot duration from shortform-narration.md's MEASURED audio durations, or from its explicitly approved alternate timing source when spoken narration is not applicable. Never fit narration to arbitrary visual clip lengths after generation. For each shot record its beat, duration, what it must prove, its location/background, lighting and palette anchors, audio intent, the resolved model id and provider, and the full generation prompt built with video-cinematography's five-aspect formula — subject, subject motion, scene, spatial framing, camera — in precise camera vocabulary rather than mood adjectives. " +
		"Do the duration arithmetic explicitly against the chosen model's per-call limit, and confirm every model id against the provider's own live reference rather than inventing one. Where a subject recurs across shots, follow video-cinematography's consistency rules: define it and its reference image first, keep its shots on one model and provider, and repeat its spec phrase verbatim. " +
		"Classify every visual as generated cinematic footage, supplied media, or a HyperFrames insert. Use a HyperFrames insert only for exact UI/screens, titles, typography, diagrams, overlays, transitions, camera moves over supplied assets, or compositing that the user wants; never use it for a photoreal subject, performance, location, or continuity-critical shot. Reserve exact text, prices, logos, and captions for the overlay layer at assembly rather than baking them into generated footage. State the total paid call count and estimated cost up front, since the next stage asks the user to approve exactly that. Generate nothing in this stage.",

	"shortform-generate": "Create the shots exactly as shortform-shotlist.md specifies after reading shortform-look-sound.md and shortform-narration.md, using fal-ai, google-ai, or seeddance-api per the provider and model recorded for each generated shot. The default is real-looking cinematic footage. For an entry explicitly classified as a HyperFrames insert, build and render only that insert with the managed HyperFrames tooling, preserve the cinematic design contract, and show its MP4 for review; do not introduce unplanned HyperFrames scenes or use them as stand-ins for photoreal footage. This stage executes an approved plan; it does not re-plan. " +
		"Where a subject recurs, use the already approved reference from shortform-characters.md and condition every later shot of it on that same reference, keeping those shots on one model and provider. Never create or silently replace the character reference during video generation. Respect the re-prompt budget from shortform-brief.md rather than spending indefinitely on one shot. " +
		"Follow shortform-look-sound.md's audio mode exactly. For separate-narration productions, generated clips may be silent visuals and every individual preview must say that narration and the final mix are added during assembly; do not present a silent visual clip as the finished video. Use native model speech only when the direction explicitly selected it and the shot list supplies the exact dialogue and review requirement. Show every generated clip individually before assembly. " +
		"Write shortform-generation.md recording, per shot: status (`generated`, `failed`, or `skipped`), the exact local file path when one exists, the resolved model id and provider, the prompt actually sent, the measured duration, audio-stream presence, and whether its audio is native dialogue, ambience/effects, silent visual preview, or unusable. A shot recorded as generated without a file on disk is a failure. " +
		generationSpendGate("video, image, or audio clips"),

	"shortform-assemble": "Assemble the cut from media that already exists. Read shortform-look-sound.md, shortform-narration.md, shortform-shotlist.md, and shortform-generation.md and resolve every input from the exact recorded paths — do not generate anything here. If a required shot or required narration segment is `failed`, missing, silent, or unreadable, stop and write shortform-render.md naming it rather than substituting an unrelated clip or silently delivering video-only output. " +
		"Follow video-editing. Normalise every clip's specs with ffprobe before concatenating. Cut tight: at this length hold shots only as long as they earn, and use video-editing's transition rules including its bias toward hard cuts between independently-generated clips. " +
		"Cut visuals to the measured narration timeline. Respect the platform's safe areas from shortform-brief.md so captions and essential subjects survive platform UI overlays, and put exact text in a deterministic overlay layer rather than baking it into footage. HyperFrames may supply exact overlays, titles, transitions, or approved inserts, but must remain inside the same cinematic edit and sound world. Add the approved narration or native dialogue, music, ambience, sound effects, and captions from shortform-look-sound.md; mix to the stated per-stem levels and delivery target. " +
		"Render shortform-final.mp4 in this step folder, verify it by full decode with ffprobe, and write shortform-render.md with every visual and audio input path, the selected background/look decisions, the narration or native-dialogue source per beat, music/ambience/effects/caption layers, the commands used, and the measured duration, dimensions, frame rate, codecs, and loudness of the result.",

	"shortform-check": qualityReviewDescription("shortform-final.mp4 as named by shortform-render.md", "shortform-delivery.md") +
		" Weight the review for short-form: confirm the hook actually lands in the opening seconds, that captions and key subjects sit inside the destination platform's safe areas at the target aspect ratio, and that the piece reads clearly at phone size and at speed. " +
		"Read shortform-look-sound.md and shortform-narration.md. When the brief requires spoken instruction, missing or silent narration is a deterministic failure and audio or captions may not be marked not_applicable. Verify narration alignment against the measured beat durations, speech intelligibility, the approved voice direction, music ducking, ambience and effects continuity, caption wording and timing, and that the final export—not merely the individual visual previews—has the promised audio. " +
		"After video-quality's checks pass, run generated-video-quality's checks against the same candidate and add their results to the same quality-report.json: character_consistency against each subject's reference (not from memory), generation_artifacts, temporal_coherence at every stitch point, prompt_adherence against shortform-shotlist.md, narration_alignment against shortform-narration.md, and lip_sync where dialogue exists. A candidate that passes video-quality but fails any of these is not ready to present.",
}

var shortformPipeline = &Pipeline{
	ID:          "shortform",
	Name:        "Short-form AI video",
	Description: "A short social cut built from AI-generated footage, shaped for one arc and a destination platform's safe areas.",
	WhenToUse:   "Short social video — reels, shorts, ads, teasers, typically under two minutes — where the footage must be generated rather than composed from uploads.",
	Stages: []PipelineStage{
		{ID: "shortform-brief", Title: "Brief and platform", Summary: "Confirm the message, platform, duration, and cost ceiling before anything is generated.", Output: "shortform-brief.md", Skills: []string{"video-creation", "video-storytelling", "video-provider-capabilities", "kling-video", "seedance-video", "seeddance-api", "veo-video", "minimax-h3-video", "gemini-omni-video", "video-model-selection"}},
		{ID: "shortform-script", Title: "Script", Summary: "Write the verbatim hook, value, and action beats.", Output: "shortform-script.md", Skills: []string{"video-storytelling", "video-creation"}},
		{ID: "shortform-characters", Title: "Choose and define characters", Summary: "Let the user choose a character model and reference pack, then approve every recurring subject before any video shot exists.", Output: "shortform-characters.md", Skills: []string{"video-cinematography", "video-model-selection", "fal-ai", "google-ai"}},
		{ID: "shortform-look-sound", Title: "Look and sound direction", Summary: "Lock locations, wardrobe, lighting, palette, voice, music, ambience, effects, and captions.", Output: "shortform-look-sound.md", Skills: []string{"video-look-sound", "video-cinematography", "video-model-selection", "video-editing"}},
		{ID: "shortform-narration", Title: "Generate narration", Summary: "Create the approved voiceover in segments and measure its real duration.", Output: "shortform-narration.md", Skills: []string{"video-look-sound", "video-editing", "fal-ai", "google-ai", "video-storytelling"}},
		{ID: "shortform-shotlist", Title: "Shot list and prompts", Summary: "Classify generated footage, supplied media, and HyperFrames inserts around the measured narration, then cost the run.", Output: "shortform-shotlist.md", Skills: []string{"video-look-sound", "video-cinematography", "video-provider-capabilities", "kling-video", "seedance-video", "seeddance-api", "veo-video", "minimax-h3-video", "gemini-omni-video", "video-model-selection", "video-editing", "hyperframes"}},
		{ID: "shortform-generate", Title: "Create shots", Summary: "Produce and individually review approved footage and any explicitly planned HyperFrames inserts.", Output: "shortform-generation.md", Skills: []string{"video-look-sound", "fal-ai", "google-ai", "seeddance-api", "video-cinematography", "video-provider-capabilities", "kling-video", "seedance-video", "veo-video", "minimax-h3-video", "gemini-omni-video", "video-model-selection", "hyperframes", "hyperframes-cli"}},
		{ID: "shortform-assemble", Title: "Assemble and mix", Summary: "Stitch cinematic visuals and approved HyperFrames layers with narration, music, ambience, effects, captions, and overlays.", Output: "shortform-render.md", Artifacts: []string{"shortform-final.mp4"}, Skills: []string{"video-look-sound", "video-editing", "hyperframes", "hyperframes-cli"}},
		{ID: "shortform-check", Title: "Audio and visual QA", Summary: "Verify picture, narration, mix, captions, timing, hook, HyperFrames inserts, and platform safe areas.", Output: "shortform-delivery.md", Artifacts: []string{"quality-report.json", "qa-contact-sheet.jpg"}, Skills: []string{"video-look-sound", "video-quality", "generated-video-quality", "hyperframes-quality"}},
	},
}
